### ISSUE TITLE
File path issue 

### ISSUE THREAD

**Issue by conorosully** [Ambrish001/Coastline_Monitoring#1]
Hi Ambrish :) 

I am working with Dr Dev on a similar project. I am trying to run your code but I'm having some issues. 

In Final_Notebook_UCD.ipynb, under the "Pre-Processing the images" section you have this line: 

name = "/content/drive/MyDrive/UCD_Research/"+s[8]+".TIF"

This is giving me an error. Do you know the correct path for saving the preprocessed images? 

Thanks
Conor

**Comment by Ambrish001** [comment]
Hi!!
I have corrected the path and updated the Notebook. Actually the input file path needed to be changed an I have changed it. I have verified it once but if any further issue arises then kindly share the problem with me.

Thank You
Ambrish

**Comment by conorosully** [comment]
Thank you! I was able to run most of the code :)
